global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: k6_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [ 'k6_exporter:9091' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: 'dbuser'
    static_configs:
      - targets: [ 'dbuser_exporter:9187' ]
  - job_name: 'dbproduct'
    static_configs:
      - targets: [ 'dbproduct_exporter:9187' ]